// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleManagementApi.Models;

namespace VehicleManagementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleManagementModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WeightFrom")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("WeightUpTo")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Light",
                            Icon = "Icon1",
                            WeightFrom = 0.00m,
                            WeightUpTo = 500.00m
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Medium",
                            Icon = "Icon2",
                            WeightFrom = 500.00m,
                            WeightUpTo = 2500.00m
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Heavy",
                            Icon = "Icon3",
                            WeightFrom = 2500.00m,
                            WeightUpTo = 5000.00m
                        });
                });

            modelBuilder.Entity("VehicleManagementModels.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<int>("Manufacturer")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            ManufactureYear = 2020,
                            Manufacturer = 3,
                            OwnerName = "Owner1",
                            Weight = 100.00m
                        },
                        new
                        {
                            VehicleId = 2,
                            ManufactureYear = 1998,
                            Manufacturer = 2,
                            OwnerName = "Owner2",
                            Weight = 10.00m
                        },
                        new
                        {
                            VehicleId = 3,
                            ManufactureYear = 1899,
                            Manufacturer = 4,
                            OwnerName = "Owner3",
                            Weight = 50.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
